"""Abstract interface for graph store backends.

Both FalkorDB and SQLite backends implement this Protocol so that the rest of
the application can depend on the interface rather than a concrete type.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class GraphStore(Protocol):
    """Minimal graph store interface shared by all backends.

    Implementors must support:
    - Node CRUD via ``add_node`` / ``get_node``
    - Edge CRUD via ``add_edge``
    - Graph traversal via ``get_neighbors``
    - Filtered search via ``search_nodes``
    - Raw query execution via ``execute_query``
    """

    async def initialize(self) -> None:
        """Create schema / open connections.

        Must be idempotent — safe to call multiple times.
        """
        ...

    async def add_node(
        self,
        node_type: str,
        properties: dict[str, Any],
    ) -> str:
        """Insert or upsert a node.

        Args:
            node_type: Label / type for the node (e.g. ``"Session"``, ``"File"``).
            properties: Arbitrary key-value pairs to store.  Must include ``"id"``
                and ``"name"`` when meaningful.

        Returns:
            The stable node ID (taken from ``properties["id"]`` if present,
            otherwise auto-generated by the backend).
        """
        ...

    async def get_node(self, node_id: str) -> dict[str, Any] | None:
        """Return a node by ID, or ``None`` if not found.

        The returned dictionary always contains ``"id"``, ``"node_type"``, and
        ``"name"`` alongside any backend-specific properties.
        """
        ...

    async def add_edge(
        self,
        from_id: str,
        to_id: str,
        edge_type: str,
        properties: dict[str, Any] | None = None,
    ) -> str:
        """Insert or upsert a directed edge between two nodes.

        Args:
            from_id: Source node ID.
            to_id:   Target node ID.
            edge_type: Relationship label (e.g. ``"MENTIONS"``, ``"USES"``).
            properties: Optional metadata to store on the edge.

        Returns:
            An opaque edge identifier.
        """
        ...

    async def get_neighbors(
        self,
        node_id: str,
        edge_type: str | None = None,
        direction: str = "outgoing",
    ) -> list[dict[str, Any]]:
        """Return nodes connected to ``node_id``.

        Args:
            node_id:   Starting node.
            edge_type: Restrict to edges of this type.  ``None`` means all types.
            direction: ``"outgoing"`` (default), ``"incoming"``, or ``"both"``.

        Returns:
            List of neighbour node dictionaries (same shape as ``get_node``).
        """
        ...

    async def search_nodes(
        self,
        node_type: str | None = None,
        name_contains: str | None = None,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Return nodes matching optional filters.

        Args:
            node_type:     Restrict to nodes of this type.  ``None`` means all types.
            name_contains: Case-insensitive substring match on the ``name`` field.
            limit:         Maximum number of results.

        Returns:
            List of node dictionaries.
        """
        ...

    async def execute_query(
        self,
        query: str,
        params: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """Execute a backend-specific query and return rows.

        For the SQLite backend this accepts a *limited* Cypher-like syntax (see
        ``SQLiteGraphStore`` for details).  For the FalkorDB backend it passes
        the query through verbatim.

        Args:
            query:  Query string.
            params: Named parameters substituted into the query.

        Returns:
            List of result row dictionaries.
        """
        ...

    async def close(self) -> None:
        """Release connections / flush write-ahead logs."""
        ...
